services:
  mariadb:
    image: mariadb:11.3.2-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db
    ports:
      - "3306:3306"

  mongo:
    image: mongo:7.0.9-jammy

    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

